import json

path = r"c:\Users\hp\Downloads\Pr-diction-de-la-Performance-des-tudiants\code\ML_student_performance_VF.ipynb"
with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb.get("cells", []):
    if cell.get("cell_type") == "code":
        source = "".join(cell.get("source", []))
        if "# 2. Définir la Target" in source:
            feature_eng = """
# ==========================================
# 🚀 FEATURE ENGINEERING PROFESSIONNEL
# ==========================================
# 1. Revenu par personne (Pouvoir d'achat réel)
df['revenu_par_personne'] = df['revenu_familial'] / (df['nombre_membres_famille'].replace(0, 1))

# 2. Total des heures d'étude par semaine (Jour x 5 + Weekend x 2)
df['total_heures_etude_semaine'] = (df['heures_etude_jour'] * 5) + (df['heures_etude_weekend'] * 2)

# 3. Ratio d'Effort (Étude vs Écran)
df['ratio_etude_ecran'] = df['total_heures_etude_semaine'] / ((df['temps_ecran_heures_jour'] * 7) + 1)

# 4. Indice de Discipline (Combinaison d'assiduité, ponctualité et remise de devoirs)
df['indice_discipline'] = (df['taux_assiduite'] + df['taux_ponctualite'] + df['taux_remise_devoirs']) / 3

# 5. Pénalité de comportement (Absences et retards)
df['penalite_comportement'] = df['absences_totales'] + df['retards']

# 6. Charge parascolaire (Soutien + Sport)
df['charge_parascolaire'] = df['heures_soutien_semaine'] + df['activite_physique_heures_semaine']

# Ajout des nouvelles variables à la liste
nouvelles_features = [
    'revenu_par_personne', 'total_heures_etude_semaine', 'ratio_etude_ecran', 
    'indice_discipline', 'penalite_comportement', 'charge_parascolaire'
]
features_socio.extend(nouvelles_features)

"""
            if "FEATURE ENGINEERING PROFESSIONNEL" not in source:
                parts = source.split("# SCÉNARIO 2 : Mi-année")
                if len(parts) == 2:
                    new_source = parts[0] + feature_eng + "# SCÉNARIO 2 : Mi-année" + parts[1]
                    
                    # Split over lines but keep newlines
                    lines = [line + "\n" if not line.endswith("\n") else line for line in new_source.split("\n")]
                    # Cleanup the last empty element if it was generated by trailing \n
                    if lines and lines[-1] == "\n":
                        lines.pop()
                    
                    cell["source"] = lines

    if cell.get("cell_type") == "markdown":
        source = "".join(cell.get("source", []))
        if "### Transformation" in source and "Feature Engineering" not in source:
            new_source = source.replace("### Transformation", "### Feature Engineering (Nouveau)\n- **Création de variables pertinentes** : Revenu par personne, Ratio Étude/Écran, Indice de Discipline, etc.\n\n### Transformation")
            lines = [line + "\n" if not line.endswith("\n") else line for line in new_source.split("\n")]
            if lines and lines[-1] == "\n":
                        lines.pop()
            cell["source"] = lines

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook updated successfully.")
